### ISSUE TITLE
win11上部署，python依赖一直过不去

### ISSUE THREAD

**Issue by yeah2569** [linyqh/NarratoAI#13]
> 402.3 Downloading rpds_py-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (354 kB)
 402.7 Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
 403.0 Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
 404.1 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the > package versions, please update the hashes. Otherwise, examine the package contents carefully; s   someone may have > tampered with them.
 404.1     unknown package:
 404.1         Expected sha256 0220fce2a62d71cc5e89617419b6224ddb43f1753b00f68b5c9af8b5f41d38c9      
 404.1              Got        42617eac5241ff34028fd4bed5d42b76526e1b00533d25374eabc67c4b33fa6f      
 404.1
 ------
failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1

**Comment by yeah2569** [comment]
about Network ?

**Comment by midpoint** [comment]
试试换一下源
