### ISSUE TITLE
TimeoutError : 上传视频至Google云失败，请检查VPN配置和APIKey是否正确； <HttpError 400 请求 None 时返回“API 使用不支持用户位置。”。详细信息：“API 使用不支持用户位置。”

### ISSUE THREAD

**Issue by lwj0308** [linyqh/NarratoAI#14]
生成了双子座的apikey，获取了Pexels API Key，视频使用的自带的demo，其他参数没有改动，科学上网没问题。
生成视频脚本报错：File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/NarratoAI/webui/Main.py", line 352, in <module>
    script = llm.gemini_video2json(
File "/NarratoAI/app/services/llm.py", line 461, in gemini_video2json
    raise TimeoutError(f"上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; {err}")

**Comment by yeah2569** [comment]
遇到同样的问题了

**Comment by linyqh** [comment]
> 生成了双子座的apikey，获取了Pexels API Key，视频使用的自带的demo，其他参数没有改动，科学上网没问题。 生成视频脚本报错：File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script exec(code, module.**dict**) File "/NarratoAI/webui/Main.py", line 352, in script = llm.gemini_video2json( File "/NarratoAI/app/services/llm.py", line 461, in gemini_video2json raise TimeoutError(f"上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; {err}")

更换vpn代理的区域； 可以尝试新加坡，日本，美国。

**Comment by lwj0308** [comment]
ok

**Comment by elepopp** [comment]
把tun mode打开
