### ISSUE TITLE
KeyError: 'st.session_state has no key "task_id"

### ISSUE THREAD

**Issue by CCC002FA7** [linyqh/NarratoAI#17]
我在配置完成后遇到了错误，还需要配置什么选项吗
I encountered an error after completing the configuration. Are there any other options that need to be set up?
![1724674483248](https://github.com/user-attachments/assets/5325db2b-260b-4975-a126-b3dc570e986d)

**Comment by CCC002FA7** [comment]
![1724674483248](https://github.com/user-attachments/assets/71ab99d8-64f4-43e0-9588-fe5d60e54f7d)

**Comment by linyqh** [comment]
> 我在配置完成后遇到了错误，还需要配置什么选项吗 I encountered an error after completing the configuration. Are there any other options that need to be set up? ![1724674483248](https://private-user-images.githubusercontent.com/157573491/361431088-5325db2b-260b-4975-a126-b3dc570e986d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDg5ODEsIm5iZiI6MTcyNDc0ODY4MSwicGF0aCI6Ii8xNTc1NzM0OTEvMzYxNDMxMDg4LTUzMjVkYjJiLTI2MGItNDk3NS1hMTI2LWIzZGM1NzBlOTg2ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTk0YmIxNjA0MGQ5ZDViZGVkZTA0MzJlNjI3YzkzNjAwZmNlODc3MzM1Njg5NmJlMmM1OWE1NjExZjZiMWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bwXqrFbj_WMxQTB5ZIitW9lsFHA1u_T47UeZ-6dU21E)

生成脚本后是否未点击剪裁，最新代码中已加上了对应错误提示！
