### ISSUE TITLE
是否可以自定义脚本，且根据脚本内容匹配视频画面并进行剪辑，合并后导出

### ISSUE THREAD

**Issue by wangdagegege** [linyqh/NarratoAI#18]
是否可以自定义脚本，且根据脚本内容匹配视频画面并进行剪辑，合并后导出？
自定义文案，根据文案描述匹配最接近的视频画面，谢谢！

**Comment by linyqh** [comment]
> 是否可以自定义脚本，且根据脚本内容匹配视频画面并进行剪辑，合并后导出？ 自定义文案，根据文案描述匹配最接近的视频画面，谢谢！

这个idea不错，会尝试在接下来的版本中加上此功能🎉
