### ISSUE TITLE
KeyError: 'st.session_state has no key "task_id". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

### ISSUE THREAD

**Issue by tuzi356** [linyqh/NarratoAI#2]
Traceback:
File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "F:\NarratoAI\webui\Main.py", line 730, in <module>
    task_id = st.session_state['task_id']
              ~~~~~~~~~~~~~~~~^^^^^^^^^^^
File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 93, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 410, in __getitem__
    raise KeyError(_missing_key_error_message(key))

**Comment by linyqh** [comment]
> Traceback: File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script exec(code, module.**dict**) File "F:\NarratoAI\webui\Main.py", line 730, in task_id = st.session_state['task_id'] ~~~~~~~~~~~~~~~~^^^^^^^^^^^ File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 90, in **getitem** return get_session_state()[key] ~~~~~~~~~~~~~~~~~~~^^^^^ File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 93, in **getitem** return self._state[key] ~~~~~~~~~~~^^^^^ File "F:\NarratoAI\venv\Lib\site-packages\streamlit\runtime\state\session_state.py", line 410, in **getitem** raise KeyError(_missing_key_error_message(key))


"Can you reproduce your steps? I didn't encounter the same error when I used the `docker compose up -d` command locally; my platform is Win11 / Mac M2; Docker version: 27.0.3."

**Comment by tuzi356** [comment]
F:\NarratoAI>docker compose up -d
'docker' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by tuzi356** [comment]
my win 10
F:\NarratoAI>docker compose up -d
'docker' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by DSKJ-18647370797** [comment]
这个好像要开通谷歌的COULD，才可以，换的绑信用卡，不然文件传不上去
，就会报错，看看能不能搞成用本地模型

**Comment by tuzi356** [comment]
> 这个好像要开通谷歌的COULD，才可以，换的绑信用卡，不然文件传不上去 ，就会报错，看看能不能搞成用本地模型

你的装好了？

**Comment by linyqh** [comment]
> 这个好像要开通谷歌的COULD，才可以，换的绑信用卡，不然文件传不上去 ，就会报错，看看能不能搞成用本地模型

我的 google 账号没有绑信用卡，就是一个普通账号

**Comment by EasonRAY1307** [comment]
> 这个好像要开通谷歌的COULD，才可以，换的绑信用卡，不然文件传不上去 ，就会报错，看看能不能搞成用本地模型

是的 我感觉我网络没问题 api也能调，token也有，就是upload缺一个buket的上传的Googlecloud 如果没开通就无法上传
