### ISSUE TITLE
卡住了

### ISSUE THREAD

**Issue by JAYOOO** [linyqh/NarratoAI#21]
不知道为什么会卡在这里，检查了key和vpn都没问题。。TimeoutError: 上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; [Errno 111] Connection refused
raceback:
File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
File "/NarratoAI/webui/Main.py", line 352, in <module>
    script = llm.gemini_video2json(
File "/NarratoAI/app/services/llm.py", line 461, in gemini_video2json
    raise TimeoutError(f"上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; {err}")

**Comment by JAYOOO** [comment]
<img width="1241" alt="截屏2024-08-27 17 40 35" src="https://github.com/user-attachments/assets/52aa9f74-6cc0-4545-8545-20a70649df13">

**Comment by 151819880412** [comment]
解决了吗？我也是卡在这里了

**Comment by JAYOOO** [comment]
没解决

**Comment by 151819880412** [comment]
> 没解决

应该是网络的问题，刚刚试了一下居然成功了

**Comment by JAYOOO** [comment]
我去你哪个国家的v

**Comment by JAYOOO** [comment]
我这Google都没问题啊，我切换很多国家

**Comment by EasonRAY1307** [comment]
俺也一样

**Comment by 151819880412** [comment]
我节点没换，之前也是一直失败，就刚才成功了一次

**Comment by JAYOOO** [comment]
不应该啊，我刚节点韩国、台湾、日本、香港、泰国、德国、美国、英国、迪拜、巴西、新加坡、澳大利亚都试过了

**Comment by EasonRAY1307** [comment]
你们是手动测试的端口吗？我的vpn软件直接就连接 根本没有端口

**Comment by JAYOOO** [comment]
我感觉是不是这个大模型有问题

**Comment by EasonRAY1307** [comment]
网络问题 不是模型问题 我感觉

**Comment by EasonRAY1307** [comment]
来拉个群 互相聊下吧。。。。。。

**Comment by 151819880412** [comment]
有的节点能访问外网但是访问不了google的一些应用
我啥配置都没动，就是成功了

**Comment by EasonRAY1307** [comment]
就是抽风感觉  这玩意

**Comment by JAYOOO** [comment]
我端口不是7890，我直接改的docker-compose.yml 文件中的 VPN_PROXY_URL

**Comment by JAYOOO** [comment]
而且google的应用我节点都全能访问来着

**Comment by EasonRAY1307** [comment]
你改了有用？
 不需要改的 这个是别的访问docker的端口，不是我们去访问的api的端口，而且网络可以用的话 根本不需要动

**Comment by EasonRAY1307** [comment]
容器的网络是 curl下就是vpn的ip

**Comment by JAYOOO** [comment]
我都试过了，没改或者改了都没用

**Comment by EasonRAY1307** [comment]
我感觉是apikey的问题。我把key删了 还是这个错误

**Comment by EasonRAY1307** [comment]
![Uploading 截屏2024-08-27 19.18.55.png…]()
感觉是这

**Comment by tonyklose1984** [comment]
大佬们解决了吗？我也是一直卡这里，用demo还成功一次，上传自己视频一直提示不成功。
