### ISSUE TITLE
机子在外国，如何关闭代理使用。

### ISSUE THREAD

**Issue by a52948** [linyqh/NarratoAI#22]
服务器在国外，本身是不需要代理的。但是不填又报错

**Comment by FlyAIBox** [comment]
同问，服务器本身可以访问外网，不需要代理

**Comment by a52948** [comment]
@AlexFly666 我解决了，直接修改docker-compose.yml文件，把代理地址的方改成''，改成两个单引号，可以直接使用，跳过代理。

**Comment by EasonRAY1307** [comment]
感谢大佬
