### ISSUE TITLE
Error: 上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by Zanedname** [linyqh/NarratoAI#29]
raise TimeoutError(f"上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; {err}")
TimeoutError: 上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; [WinError 10061] 由于目标计算机积极拒绝，无法连接。

#大佬，点击执行视频脚本，换了梯子和账号，测试了几回都无法正常上传，

**Comment by linyqh** [comment]
试试从配置文件中更改 proxy 
- 编辑配置文件 config.toml
- 修改 [proxy] 如下图：
![image](https://github.com/user-attachments/assets/311108ef-5097-4141-8bba-ec3cdae7b340)

如果是使用 docker 启动的，proxy 地址需要更换为： `http://host.docker.internal:7890`

**Comment by wanquanY** [comment]
![image](https://github.com/user-attachments/assets/0ff86eeb-adff-42e5-bd45-1fdd08e2b404)
呃，用了自己的梯子和7890端口的都不行

**Comment by wanquanY** [comment]
这个gemini_video2json为啥用的gemini-1.5-pro、呃，切片之后上传用chatgpt跟符合习惯，没用过gemini，【冷汗】

**Comment by elongluanjiao** [comment]
大佬们老是出现这个情况怎么回事啊：ServiceUnavailable: 503 The model is overloaded. Please try again later.
![image](https://github.com/user-attachments/assets/e389c7a9-a265-4016-b7d1-3f87a2552e50)

**Comment by qbz441011816** [comment]
看来这个问题是很多人最后的阻碍，希望可以有一个详细的故障排查方式来解决问题。谢谢
<img width="945" alt="image" src="https://github.com/user-attachments/assets/c834e1c8-1502-4466-af78-559aa1a42f3d">

**Comment by linyqh** [comment]
可参考常见问题来排查问题：https://thread-marsupial-df8.notion.site/105866888dab80988650fa063b1df4eb
