### ISSUE TITLE
配置完无法运行

### ISSUE THREAD

**Issue by dou1231993** [linyqh/NarratoAI#3]
嗯… 无法访问此页面127.0.0.1 已拒绝连接。
请尝试：

在必应中搜索 [127 0 0 1]
检查连接
[检查代理和防火墙]

**Comment by linyqh** [comment]
> 嗯… 无法访问此页面127.0.0.1 已拒绝连接。 请尝试：
> 
> 在必应中搜索 [127 0 0 1] 检查连接 [检查代理和防火墙]

需要确保docker容器内 8501 正常启动，启动完成后，就能正常访问
