### ISSUE TITLE
It's not very useful at all. I thought it could be used for movies and film commentary! I've been making a scene for half a day and can only provide a maximum of 2 minutes of video commentary

### ISSUE THREAD

**Issue by haisheng666** [linyqh/NarratoAI#30]
It's not very useful at all. I thought it could be used for movies and film commentary! I've been making a scene for half a day and can only provide a maximum of 2 minutes of video commentary

**Comment by linyqh** [comment]
![Uploading image.png…]()
https://ai.google.dev/gemini-api/docs/vision?lang=python#prompting-video
