### ISSUE TITLE
400 Please use fewer than 3600 images in your request to models/gemini-1.5-flash

### ISSUE THREAD

**Issue by JxiaoC** [linyqh/NarratoAI#33]
使用一个长度为55分钟的电视剧视频进行测试，在生成视频脚本的时候出现了这个错误提示：400 Please use fewer than 3600 images in your request to models/gemini-1.5-flash

**Comment by longzy1** [comment]
一样的出错  查了半天 谷歌API不能超过3600张图片 25帧 的话 就是2分钟多一点

**Comment by linyqh** [comment]
google gemini 官方说模型可支持最长 1 小时的视频长度； 建议使用 gemini-1.5-pro 试试

![image](https://github.com/user-attachments/assets/6547fb2e-2b8b-479f-9282-ab3b8d5d3586)
