### ISSUE TITLE
上传视频至 Google cloud 失败, 请检查 VPN 配置和 APIKey 是否正确; [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by King79017** [linyqh/NarratoAI#34]
![666png](https://github.com/user-attachments/assets/29b42cbc-b3bd-40ac-867a-4e22424327d8)

**Comment by linyqh** [comment]
google api 的限制，目前只能尝试更换工具，详细可参考常见问题：
https://thread-marsupial-df8.notion.site/105866888dab80988650fa063b1df4eb

**Comment by Nswhisper** [comment]
像是dns问题，谷歌翻译就有这个问题，看过一个办法，直接使用谷歌翻译会失败，但是clash开一下系统全局，只要成功一次，关掉全局后续就可以了。同理，我用这个办法是可以的
