### ISSUE TITLE
音频设置不可用

### ISSUE THREAD

**Issue by CreepYC** [linyqh/NarratoAI#44]
语音接口用不了azure_tts_v1 - failed, error: 403, message='Invalid response status'
请问哪个文件可以更换接口 或者使用本地的
![b78510f4bf140ffb16e26411b0b7ca0](https://github.com/user-attachments/assets/6717e45c-04ab-4a77-a66b-fc925a78e86f)

**Comment by CreepYC** [comment]
这是网络问题 还是接口问题啊

**Comment by 2981717048** [comment]
升级edge_tts就可以了

**Comment by CreepYC** [comment]
> 升级edge_tts就可以了

请问在哪设置啊 或者是哪个文件 详细说一下
万分感谢！

**Comment by linyqh** [comment]
已更新requirements.txt中 edge-tts到最新版本
