### ISSUE TITLE
生成V2语音报错

### ISSUE THREAD

**Issue by 360PB** [linyqh/NarratoAI#57]
ERROR | "./app/services/voice.py:1097": azure_tts_v1 - failed, error: Invalid voice 'zh-CN-XiaoxiaoMultilingualNeural-V2'.

**Comment by linyqh** [comment]
V2 需要微软的 api key，微软的key需要海外信用卡，如果没有建议不要使用 v2 tts

**Comment by 360PB** [comment]
![image](https://github.com/user-attachments/assets/de6f539a-7692-4e07-bbf3-b57c16baccec)

使用MoneyPrinterTurbo 测试V2语音是可以的; 应该是代码有问题

**Comment by linyqh** [comment]
升级最新版本试试
