### ISSUE TITLE
docker webui.sh: line 2: $'\r': command not found

### ISSUE THREAD

**Issue by 714274808** [linyqh/NarratoAI#6]
![PixPin_2024-08-21_08-50-03](https://github.com/user-attachments/assets/258beb6e-08a1-4d9d-b493-4d3dd5272fe1)

**Comment by linyqh** [comment]
这是由于 windows 和 linux 换行符编码不一致导致的；可以尝试使用 dos2unix 工具对 webui.sh 文件进行转码
