### ISSUE TITLE
生成视频步骤，终端报错

### ISSUE THREAD

**Issue by georgehawkk** [linyqh/NarratoAI#65]
已经完成了API的设置，连通正常
视频脚本配置正常，点击生成视频后，webui弹提示
![屏幕截图 2024-11-26 204813](https://github.com/user-attachments/assets/74577ff5-f72d-4a18-a10d-e422dc2d9987)

同时终端报错：
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

**Comment by DAO-918** [comment]
我也遇到同样的问题，在配置文件中    device="CPU"   compute_type="int8" 
![图片](https://github.com/user-attachments/assets/a0c0183e-959d-4bcd-a2e1-30ac1080f161)

**Comment by linyqh** [comment]
cuda用不了的话，建议使用 cpu
