### ISSUE TITLE
生成视频脚本会出现网络问题

### ISSUE THREAD

**Issue by EasonRAY1307** [linyqh/NarratoAI#9]
<img width="1254" alt="截屏2024-08-23 21 36 30" src="https://github.com/user-attachments/assets/ccd80a70-d85e-41b4-9f6e-6b678f0e21b5">
可是已经配置了key，虽然没有配置代理，但是网络是可以访问外网的，用的梯子的原因吗？

**Comment by linyqh** [comment]
> <img alt="截屏2024-08-23 21 36 30" width="1254" src="https://private-user-images.githubusercontent.com/152354115/360945675-ccd80a70-d85e-41b4-9f6e-6b678f0e21b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2Mzk0ODEsIm5iZiI6MTcyNDYzOTE4MSwicGF0aCI6Ii8xNTIzNTQxMTUvMzYwOTQ1Njc1LWNjZDgwYTcwLWQ4NWUtNDFiNC05ZjZlLTZiNjc4ZjBlMjFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwMjI2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWNkMGQ5OTBlOWJmMzMwYWIwOTBjMzliYzRkYmEzYTZlNWY5ZjcyZmQzNWI1ZDc0NWY3YWZlYjU3MzA1ZDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OVpyMAXqyvZePXMLsste_8YMBUUNL4cuMJ6hZH2O_YY"> 可是已经配置了key，虽然没有配置代理，但是网络是可以访问外网的，用的梯子的原因吗？

docker-compose.yaml 中有一行       
```
- "VPN_PROXY_URL=http://host.docker.internal:7890"
```
是指的将本机的代理服务，映射到容器内，如果没有开启代理，容器内可能会存在网络问题；关于容器内和容器外，代理网络是否共通的问题；还需要上网查证；

**Comment by EasonRAY1307** [comment]
感谢
